Bootstrap: localimage
From: sequana.img

%labels
    Author thomas cokelaer
    Version v1.0


%post

    export PATH=$PATH:/usr/local/anaconda/bin
    pip  install sequana_fastqc

    # install dependencies
    conda install  fastqc

%runscript
    echo "Welcome to sequana fastqc pipeline"
    exec sequana_pipelines_fastqc --version
    exec sequana_pipelines_fastqc "$@"


